name: Feature
description: Feature from MXL Requirement
labels: []
assignees: []
title: "[Feature] <short description>"

body:
  - type: input
    id: requirement_link
    attributes:
      label: Requirement Issue Link
      description: Link to the related issue in MXL Requirements repo (e.g., `dmf-mxl/mxl-requirements#99999` or full URL)
      placeholder: "dmf-mxl/mxl-requirements#99999"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature
      placeholder: "Describe the feature"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Include any relevant background, links, or images."
    validations:
      required: false

# SPDX-FileCopyrightText: 2025 Contributors to the Media eXchange Layer project.
# SPDX-License-Identifier: Apache-2.0

