services:
  init:
    image: alpine
    command: ["sh", "-c", "mkdir -p /dev/shm/mxl"]
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
    restart: "no"

  writer-media-function:
    image: mxl-writer
    depends_on:
      - init
    build:
      context: ..
      dockerfile: examples/Dockerfile.writer.txt
    restart: unless-stopped
    volumes:
      - type: bind
        source: /dev/shm/mxl
        target: /domain
        
  reader-media-function:
    image: mxl-reader
    depends_on:
      - init
    build:
      context: ..
      dockerfile: examples/Dockerfile.reader.txt
    restart: unless-stopped
    volumes:
      - type: bind
        source: /dev/shm/mxl
        target: /domain
    stdin_open: true
    tty: true
